Adjust board background to new design of tasks app
nextcloud/deck pull request #2166
Opened 2020-08-01 15:34 UTC by simonspa

* Target version: master 

### Summary

This adjusts the background of boards to be slightly darker, following the recent design change in the Tasks app (https://github.com/nextcloud/tasks/pull/1136). i think the individual cards stick out better from this background.

![image](https://user-images.githubusercontent.com/1677436/89104776-200b3680-d41c-11ea-9f9a-d38df9d7bb1b.png)

This would of course be quite a change that, I guess, should be discussed (also cc'ing @jancborchardt here...)

Also, with stronger visual distinction between board and app sidebar, it feels like the sidebar elements are too close to its edge.

### Checklist

- [X] Code is properly formatted
- [X] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [X] Documentation (manuals or wiki) has been updated or is not required

2020-08-19 20:47 UTC, juliushaertl commented
@jancborchardt What do you think? I think it still could be a bit lighter than the default background-dark

2020-10-12 11:13 UTC, karlitschek commented
Hmm. I'm not sure. Looks a bit boring and old school. ;-) Maybe make the background a bit lighter. Maybe some more rounded corners of the cards. And in general maybe take some inspiration from the new dashboard? @juliushaertl @jancborchardt

2020-10-12 12:23 UTC, jancborchardt commented
Several points or questions here:
- Do we really want to go with a non-white background in general? As this will make the Deck app look separate from the rest of Nextcloud apps
- If we go with non-white, it shouldn’t be so dark. Needs to be an off-white and not grey, like e.g. `#f7f9fc` (tinted slight blue, should possibly be adjusted based on the primary theming color)
- Do we even want to go with e.g. simply the background image of the Dashboard?
- Agree with Frank we can go with more rounding of the cards, like `var(--border-radius-large)`

2020-10-12 12:34 UTC, raimund-schluessler commented
For Tasks we introduced a grey background with https://github.com/nextcloud/tasks/pull/1136. Having it equal in Deck would make sense, I think.

The background image from Dashboard could also be nice, then you could choose whether an image or plain color or whatever is shown (ideally complemented by the ability to select a different background color than the primary one for the Dashboard).

2020-10-12 12:40 UTC, juliushaertl commented
> Do we really want to go with a non-white background in general? As this will make the Deck app look separate from the rest of Nextcloud apps

I personally prefer the white one as well, but we have this request from time to time where people suggest to add some more contrast between cards and the background.

> If we go with non-white, it shouldn’t be so dark. Needs to be an off-white and not grey, like e.g. #f7f9fc (tinted slight blue, should possibly be adjusted based on the primary theming color)
> Agree with Frank we can go with more rounding of the cards, like var(--border-radius-large)

The screenshot in here was a bit outdated, the border radius is already adjusted. Here is an updated one with the slight blue-ish background as you proposed. Would be fine by me this way:

![image](https://user-images.githubusercontent.com/3404133/95747231-6096f400-0c98-11eb-8f01-7c2170c380e4.png)

> Do we even want to go with e.g. simply the background image of the Dashboard?

I personally think that a background image adds a lot of distraction from the actual content, so I'd rather not have this by default at least.

2020-11-05 21:07 UTC, juliushaertl commented
@simonspa Mind to adjust that to the proposal above and rebase? :)

2020-11-05 21:07 UTC, juliushaertl requested changes
@simonspa Mind to adjust that to the proposal above and rebase? :)

2020-11-09 20:56 UTC, juliushaertl commented
Moving the milestone, since we would need a server css variable first as discussed via chat.

2021-07-21 00:45 UTC, closed without merging