Adding a description icon to cards when they contain a description without any checkmarks
nextcloud/deck pull request #2626
Opened 2020-11-28 20:11 UTC by MonkeySon

* Resolves: #1873 
* Target version: master 

### Summary

Adding a description icon to cards when they contain a description without any checkmarks.

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is **not required**

2020-11-30 13:32 UTC, juliushaertl commented on src/components/cards/CardBadges.vue
> +		<div v-else-if="card.description && checkListCount == 0" class="icon icon-description" />
```suggestion
		<div v-else-if="card.description.trim() && checkListCount == 0" class="icon icon-description" />
```

To make sure that a description only containing spaces is not showing up.

2020-11-30 13:32 UTC, juliushaertl requested changes
Thanks for your pull request. I've added a minor comment, otherwise :+1:

2020-11-30 14:00 UTC, juliushaertl commented
Mind to rebase and squash your comments? Then the DCO check should also be happy without the merge commit :)

2020-11-30 14:21 UTC, MonkeySon commented
Sorry I am rather new to git pull requests, rebases and squashes.
If I understand you correctly, I should merge (= squash)  the last two commits (Merge & "Ignore descriptions that only contain spaces")?

2020-11-30 15:03 UTC, MonkeySon commented
Ok, I added the DOC to the latest commit, but I don't know how to get rid of the empty merge (master -> add-description-icon) commit.
I tried the command `git rebase -i HEAD~2`, but it does not include merge commits.

2020-12-28 14:48 UTC, juliushaertl approved these changes

2020-12-28 14:48 UTC, merged

2020-12-28 14:49 UTC, juliushaertl commented
>  Now, after I manually signed-off the last commit, everything should be conform. Am I right with this assumption?

Yes, that is all fine now. Thanks a lot for your pull request :)