fix: add horizontal scrollbar into the large table inside description
nextcloud/deck pull request #3531
Opened 2022-01-12 16:53 UTC by luka-nextcloud

Signed-off-by: Luka Trovic <luka@nextcloud.com>

* Resolves: #2642
* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-01-12 17:22 UTC, juliushaertl commented on src/components/card/Description.vue
> +	overflow-x: scroll;
Haven't tried out yet, but would `auto` also work maybe to not always have a scorllbar?

2022-01-14 22:02 UTC, juliushaertl commented on src/components/card/Description.vue
> +	overflow-x: scroll;
```suggestion
	overflow-x: auto;
```

Let's drop the max-content as that would also avoid long lines to break - and the auto seems to work fine to not always have a scrollbar in some browsers.

2022-01-14 22:02 UTC, juliushaertl requested changes
See inline 😉

2022-01-18 16:44 UTC, eneiluj approved these changes
:+1:

2022-01-19 10:14 UTC, mejo- approved these changes

2022-01-19 10:16 UTC, eneiluj commented
/rebase

2022-01-19 11:13 UTC, merged