Timestamps on created and modified at values
nextcloud/deck pull request #3532
Opened 2022-01-12 17:07 UTC by luka-nextcloud

Signed-off-by: Luka Trovic <luka@nextcloud.com>

* Resolves: #2818
* Target version: master 

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

2022-01-12 17:16 UTC, juliushaertl commented on src/components/card/CardSidebar.vue
> +		:subtitleTooltip="subtitleTooltip"
Mind to fix the eslint warning?

src/components/card/CardSidebar.vue#L28
Attribute ':subtitleTooltip' must be hyphenated

2022-01-12 17:17 UTC, juliushaertl commented
Otherwise looks good, LGTM once linter is happy :+1:

2022-01-18 16:35 UTC, eneiluj requested changes
This is not a big difference but I would prefer passing the timestamp directly to `moment` instead of calculating the milliseconds and building a Date object.

What do you think?

2022-01-18 16:35 UTC, eneiluj commented on src/components/card/CardSidebar.vue
> +			return t('deck', 'Modified') + ': ' + this.formatDate(new Date(this.currentCard.lastModified * 1000)) + '\n' + t('deck', 'Created') + ': ' + this.formatDate(new Date(this.currentCard.createdAt * 1
```suggestion
			return t('deck', 'Modified') + ': ' + this.formatDate(this.currentCard.lastModified) + '\n' + t('deck', 'Created') + ': ' + this.formatDate(this.currentCard.createdAt)
```

2022-01-18 16:35 UTC, eneiluj commented on src/components/card/CardSidebar.vue
> +			return moment(date).locale(this.locale).format('LLLL')
```suggestion
		formatDate(timestamp) {
			return moment.unix(timestamp).locale(this.locale).format('LLLL')
```

2022-01-20 08:59 UTC, eneiluj approved these changes

2022-01-20 09:00 UTC, merged