Next cloud deck table scrolling
nextcloud/deck pull request #5377
Opened 2023-12-14 14:57 UTC by adshrest

Description:
Currently, when a table is created within a Deck card description, and the table width exceeds the display-box width, users have to use a touchpad to scroll horizontally. This can be inconvenient, as there are no visible horizontal scrollbars indicating additional columns.

Proposal:
I suggest implementing a horizontal scrollbar for tables within the Deck card description. This can be achieved with a simple CSS tweak, such as adding overflow-x: scroll; to the relevant style.

2023-12-15 16:48 UTC, juliushaertl commented on css/deck.css
> +}
I don't think we need this duplicate rule over here, best would be to only adjust this in the component that renders the table which would be here: https://github.com/nextcloud/deck/blob/9e41cb162de805677f50dff34874ef0430db47de/src/components/card/Description.vue#L52

2023-12-15 16:49 UTC, juliushaertl commented on css/deck.css
> +}
Note the scoping might limit the css rule so you probably need something like
```css
.description__text:deep(table) {
```

2023-12-15 16:50 UTC, juliushaertl requested changes
Thanks for your contribution. I left a comment inline about where to best apply this change. 

Please also make sure that your commits have a sign-off message and best squash the changes into one commit once done.

2024-01-18 07:57 UTC, juliushaertl commented
Hi @adshrest Would you still be up for addressing the comments? Let me know if there are any questions.

2025-01-02 14:51 UTC, juliusknorr commented
Thanks again for your contribution. I'll close this as there is no further feedback. I also checked the scroll behaviour right now and for me it seems ok on latest main branch.

Feel free to reopen this if still valid by addressing the review feedback.

2025-01-02 14:51 UTC, closed without merging