Cleaning up unused indicies, fixes #5520
nextcloud/deck pull request #5612
Opened 2024-02-22 12:11 UTC by mintsoft

* Resolves: # 
* Target version: main

### Summary

Adding migration to cleanup these unused indicies; I have absolutely no idea what is going on with the naming convention on the filename/class so I've made something up.

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required

2024-02-29 08:00 UTC, juliushaertl requested changes
Thanks for your contribution. I left two small comments, maybe you can adjust that.

In addition please also comment out the index creation in the original migrations so that on new installations we do not need to run those.

2024-02-29 09:04 UTC, mintsoft commented
All done

2024-05-02 14:49 UTC, mintsoft commented
@juliushaertl polite reminder about this PR, I've just rebased and such so it's ready

2024-05-09 11:14 UTC, juliushaertl approved these changes

2024-05-09 11:24 UTC, merged