feat: Implement reference resolving for cards that have a link in the title
nextcloud/deck pull request #6286
Opened 2024-09-01 10:00 UTC by juliushaertl

Signed-off-by: Julius Härtl <jus@bitgrid.net>

* Resolves: # 
* Target version: main

### Summary

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

2025-01-03 08:46 UTC, juliusknorr commented
Ready for review. I dropped a small performance optimization but that was causing more issues and is rather a micro-optimization (see last commit).

2025-01-08 11:57 UTC, grnd-alt requested changes
the menu button for inline title edit causes issues. When editing the title, the display name is in the input field. It's very easy to edit that displayname title thinking it will keep the url reference. I think we should either have a url field (so users can change the title), or change the editing title to the url in the UI when clicking edit Title

2025-01-08 11:57 UTC, grnd-alt commented on src/components/cards/CardItem.vue
>  				</h4>
the card.title is somehow not shown when triggerEditTitle is called. The user still edits the displayTitle.

2025-01-14 22:20 UTC, juliusknorr commented on src/components/cards/CardItem.vue
>  				</h4>
Should be fixed, there was some odd behaviour around contenteditable that I could only fix by using a key property on the two elements. Otherwise it seems some parts of the dom were not updated properly.

Added a cypress test as well for the renaming.

2025-01-15 10:52 UTC, grnd-alt approved these changes
🎉

2025-01-15 10:52 UTC, merged